### PR TITLE
height and width constraints are not on superview

### PR DESCRIPTION
**Pull request by cowgp**
existing code for constraint getters always looked for the constraint on the target view's superview, but height and width constraints are not on superview, rather the target view itself.  Also added leading, and trailing getters.

### CODE REVIEW

**Comment by s4cha** [comment]
Hello @cowgp,

First of all, thank you so much for taking the time to submit a PR, this is really appreciated.

The `width` and `height` methods create constraints on the superview ->
[Stevia+size](https://github.com/s4cha/Stevia/blob/master/Stevia/Stevia/Stevia/Source/Stevia%2BSize.swift) so I think this PR would unfortunately break existing code.

As a side note, this is done purposefully, as I understand it, it's a good thing to add constraints on the superview rather than the view itself. It enables to use the view in different contexts and different view hierarchies.

In order to enforce a specific size on a view, regardless of its context,  overriding 
`func intrinsicContentSize() -> CGSize {` is the way to go.

I like that you added Leading and Trailing getters ;)

Let me know what you think,
Cheers,

**Comment by cowgp** [comment]
Hey @s4cha  - interestingly - it appears apple might be changing.  
I can do  something like:
`layout([
            100,
            |-button1-| ~ 48,
            20,
            ])`
And then if I ask for the width or height constraint of button1 it actually doesn't matter whether the code looks for it on the superview or the view itself, the correct constraint is returned from both.  However, I've actually ended up using Stevia in a hybrid situation, I'm doing iOS 9+ and thus have been taking a shot with NSLayoutAnchors and UILayoutGuides and then mixing in Stevia for styles and the convenience sugar like tap/text/image and then rather than having to ivar all my constraints that I want to animate, I've starting using these convenience getters for the constraints.   In doing so, it turns out that setting a widthAnchor or heightAnchor makes the constraint only appear on the the view itself and NOT the superview.   Have a look into it.

**Comment by cowgp** [comment]
Updated PR to stay current with 2.2.1 release and remove conflicts

**Comment by s4cha** [comment]
@cowgp 
Sorry for taking so long to address this :/
After review I completely agree with your points above
Thanks for your patience :)

**Pull request merged**
