### PR TITLE
Add links to versions tags

### PR DESCRIPTION
**Pull request by ezisazis**

### CODE REVIEW

**Comment by s4cha** [comment]
@ezisazis  Wouldn't it be better to link the releases ? (such as https://github.com/freshOS/Stevia/releases/tag/4.2.0)
or maybe both ?

**Comment by ezisazis** [comment]
You are right, I'm going to do that. (and for the other PRs too)

**Comment by s4cha** [comment]
@ezisazis this is just a note, I understand that some might prefer the git tag rather than the pre-packaged `.framework`. I tend to use the latter but understand some might prefer otherwise.

**Comment by s4cha** [comment]
We tend to always generate `.framework` whenever that makes sense, which makes it way faster for the Carthage users (the dependency manager doesn't have to clone and build the project locally) :)

**Pull request merged**
